services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file: .env
    networks:
      - shared
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  shared:
    external: true
