services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: polvo-dev
    working_dir: /app
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - REDIS_URL=redis://redis:6379
    volumes:
      # IMPORTANT: run `docker compose` from WSL in the WSL repo path so '.'
      # is the Linux filesystem, not C:\.
      - .:/app
      - node_modules:/app/node_modules
      - vite_cache:/app/.vite
      - svelte_kit:/app/.svelte-kit
      - media_data:/data/avatars
      # - /mnt/c/Users/joshb/Documents/media_backup:/backup
    networks:
    - shared
    # make sure host.docker.internal resolves in Linux containers
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:8.2.1-alpine
    restart: always
    container_name: polvo_redis_dev
    ports:
      - "6379:6379"
    networks:
      - shared
  
  postgres_polvo:
    image: postgres:16
    container_name: mydb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_POLVO}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_POLVO}
      POSTGRES_DB: ${POSTGRES_DB_POLVO}
    volumes:
      - pgdata_polvo:/var/lib/postgresql/data
      - ./polvo-docker-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    entrypoint: ['/bin/sh', '-c', 'rm -rf /var/run/postgresql/* && docker-entrypoint.sh postgres']
    networks:
      - shared




volumes:
  media_data:
  node_modules:
  vite_cache:
  svelte_kit:
  pgdata_polvo:

networks:
  shared:
    external: true
