FROM node:25-alpine3.22 AS dev
WORKDIR /app

# install deps first (better layer cache)
COPY package.json package-lock.json* ./
RUN npm ci

# you'll bind-mount the rest of the source in compose
EXPOSE 5173
CMD ["npm","run","dev","--","--host","--port","5173"]

